### ISSUE TITLE
Linter not work on windows 10

### ISSUE THREAD

**Issue by machsix** [krvajal/vscode-fortran-support#116]
I'm using windows 10 with gfortran installed through msys2. I have set the location of gfortran as `C:\msys64\usr\bin\gfortran.exe`. Extension like FORTRAN IntelliSense work without problem.  However, linter doesn't work even for a simple code like the following
```
program main
    implicit none
    x = 1
    y = 1
    write(*,*) x
end program
```
The problem panel is empty. Whenever I save the file, the following information pops up in the console of developer tool:
```
[Extension Host] child process exited with code false
```

I have tried to add `C:\msys64\usr\include` to the path of include, it doesn't help. Thanks for your help and I would like to provide other information needed.

**Comment by pedro-ricardo** [comment]
I'm very sorry @machsix but I can't help you with that. I've never tested the extension in any windows and won't install one just to do so =].
But Pull Requests are always welcome. 
If you find the time, take a look at the code and see if you can debug what is wrong in your OS. It's probably something simple, since we had a merged pull request (#10) to solve aparently that same thing.
