### ISSUE TITLE
incorrect bracketing "(//))"

### ISSUE THREAD

**Issue by lonelykid** [krvajal/vscode-fortran-support#148]
An additional round bracket is inserted. (//) this syntax is used for assigning values for an array.
![rec](https://user-images.githubusercontent.com/2936633/65445633-ab7d6980-de00-11e9-89d6-6c3b46e4199a.gif)
Is this controlled by this extension?

**Comment by pedro-ricardo** [comment]
Yes it is ! Thank you for the feedback.

This is the part that controls it... It should be simple but it seems to be accumulating rules. 
![Screenshot_2019-09-27_19-30-02](https://user-images.githubusercontent.com/15893711/65805774-48bc0300-e15d-11e9-91a6-f6cad5d9bae9.png)

I'll have a look into it.

**Comment by pedro-ricardo** [comment]
This change in **language_configuration.json** appears to fix it ...
![Screenshot_2019-09-27_19-36-04](https://user-images.githubusercontent.com/15893711/65805994-1232b800-e15e-11e9-92ad-c8a3cb2d5d15.png)

Due to the first bracket is automatic closed, the close option of the array constructor don't need to have the `)` again. But i can't prove that it will work all the time yet

**Comment by pedro-ricardo** [comment]
By the way ... The usage of `(\ \)` as array constructor is outdated, I suggest you to use the new symbol: `[ ]`.

**Comment by lonelykid** [comment]
Ok. Thank you for the update and suggestion.
This is not perfect, but looks like this is what you can do here.
