### ISSUE TITLE
Commenting in fixed form fortran

### ISSUE THREAD

**Issue by thijssteel** [krvajal/vscode-fortran-support#160]
I have some problems with the commenting when writing fixed form fortran. I'm not entirely sure this library is responsible for vscode's behaviour, so apologies in advance.

Let's say I have the following fixed form fortran code
```
*     some comment
      call foo()
```
If I press `ctrl + /` on the second line, it will produce the following
```
*     some comment
      ! call foo()
```
I would much prefer it if it would produce the following lines
```
*     some comment
*     call foo()
```

The "!" character at the start of the line would also be acceptible as a default. Perhaps it would even be possible to automatically detect which character is being used in the rest of the file for consistency.

**Comment by gnikit** [comment]
I believe this is a feature of VSCode and not related to the Modern Fortran extension. For VS Code this makes sense because it allows you to create foldable scopes even when the extension authors have not explicitly defined a [Language Server Folding](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding).

If you don't care about foldable scopes and still want 0 column comments you can:
1. use multicursors which are native to VS Code
2.  use something like this: https://stackoverflow.com/questions/59418108/make-comments-of-vscode-start-at-column-position-0

For the reason stated above this is unlikely to be implemented as part of the extension so I will be closing this issue.
