### ISSUE TITLE
!$ syntax highlighting for Fortran module usage

### ISSUE THREAD

**Issue by Walkyure** [krvajal/vscode-fortran-support#17]
Hey, you guys do awesome work. like seriously being able to code fortran in VSC is amazing. I just have one suggestion. When implementing !$ it comes out as a comment, anyways to change this so that is shows the module being called? 

for example:

![image](https://user-images.githubusercontent.com/32920613/34186809-0ea6f82e-e582-11e7-81e3-d1f14c9445e9.png)

I am calling the omp_lib module, but it shows up as a comment

**Comment by krvajal** [comment]
I don't know a better way to do this as it is, in fact, a comment in the sense of the Fortran language itself. I have to do some research on how openMP comments are highlighted by other languages.
Maybe something similar to what it actually does with #27

**Comment by Walkyure** [comment]
Yeah it is quite similiar to #27 is asking about, I will take a look into the extension code and see whether I can help, other than that. Really appreciate your work man with this extension.

**Comment by pedro-ricardo** [comment]
@Walkyure, can you provide us with a screenshot of this call
`!$ call omp_set_num_threads(num_threads)`
where it is colored properly (from another text editor I mean).

**Comment by krvajal** [comment]
Check #66

**Comment by pedro-ricardo** [comment]
Looks great! I think you can close this.

**Comment by krvajal** [comment]
Cool, lets make the extension better.

**Comment by pedro-ricardo** [comment]
Last commit (#66) made all user variables on file to be highlighted. In fact every thing you type is now highlighted some how. Don't know if this was the intention... or is a collateral effect from openmp directives.

**Comment by krvajal** [comment]
The effect you are seen is mostly related to this change https://github.com/krvajal/vscode-fortran-support/pull/66/files#diff-616233c5d0603b2d6f6659138ad22463R5109.
It seems that the variables scope in the syntax is too wide and it flags everything as a variable. 
The easy solution is to revert this change, the hardest one is to actually create a proper scope for var parameters and apply the highlighting there.

**Comment by pedro-ricardo** [comment]
What are you calling "var parameters"? Other than inside a function or subroutine declaration when does a variable needs to be highlighted?

**Comment by pedro-ricardo** [comment]
Let me put it another way ... I agree with the usage of `variable.parameter.fortran` scope and with the attempt to standardize the scopes used. 
What i don't agree is that we have a rule so general as the below one, that covers anything the user types.
```
"variable": {
    "name": "variable.parameter.fortran",
    "begin": "(?i)\\b(?=[a-z])",
    "end": "(?<!\\G)",
```
When it is not a keyword or a feature from the language it should be only in the scope `source.fortran.free`, like it was in the earlier versions of the extension.
In the images below i written something in a blank file ...

Here is what happens today:
![new](https://user-images.githubusercontent.com/15893711/40581836-9abd1eec-6138-11e8-9192-f28c41a3dc0f.png)
Here is how it used to be (and what i agree with):
![old](https://user-images.githubusercontent.com/15893711/40581838-abda9c7c-6138-11e8-9fdb-2ad40d37bed9.png)

Since we have `variable.parameter.fortran` scope in the places that need it like in `"dummy-variable"` rule, for example. I think we should remove the above "variable" rule.
I've tested it and works just fine, will commit the removal to hotfix/highlight branch and you take a look.
