### ISSUE TITLE
Cannot evaluate any Debug Console REPL command

### ISSUE THREAD

**Issue by ToonWeyens** [krvajal/vscode-fortran-support#193]
Whatever I do, I always get `-var-create: unable to create variable object`. For example:
    
    write(*,*) 'test'
    -var-create: unable to create variable object

I can use the lower-level GDB commands with `-exec`, but that's a pain ...

It looks to me like this is a configuration problem, though?

Please let me know if I can provide any follow-up information, and thanks a lot!

**EDIT**
Just to be sure, I started a new hello-world c++ project, following the official [cpp tutorial](https://code.visualstudio.com/docs/cpp/config-linux).

When I then do a simple 

    cout << "hello world";

I get the same error: `-var-create: unable to create variable object`. This means that it's not a fortran-related thing probably? 

I will repost this question in the [vscode-cpptools repo](https://github.com/microsoft/vscode-cpptools/issues/6259)

**Comment by gnikit** [comment]
Could you maybe provide some more details to replicate the behaviour, maybe a minimal working example, because I am having problems with GDB and Fortran that I did not previously encounter when I added the debugger support for the extension.

**Comment by ToonWeyens** [comment]
Hi @gnikit , I was using a very convoluted enormous example, so I don't think passing that to you will help.
However, I then moved on and made a tiny minimal working example using C++, and I got the same errors.

I posted it in this issue https://github.com/microsoft/vscode-cpptools/issues/6259.

Do you get similar issues?

**Comment by gnikit** [comment]
> Hi @gnikit , I was using a very convoluted enormous example, so I don't think passing that to you will help.
> However, I then moved on and made a tiny minimal working example using C++, and I got the same errors.
> 
> I posted it in this issue https://github.com/microsoft/vscode-cpptools/issues/6259.
> 
> Do you get similar issues?

I see, I am not sure but from what I know you can't use the VS Code debugger like a normal GDB terminal. I could be wrong of course so better stick to what the Microsoft guys tell you.

My issue is related to inspecting pointers of custom type objects, which seem to have magically stopped working and cause the entire GDB session to abort which is annoying.

**Comment by gnikit** [comment]
Coming back to this, unfortunately we cannot do anything with regards to this issue. This behaviour has to do with GDB and how it handles Fortran intrinsic functions. So if you launch GDB from a terminal and try and call `sin(x)` for example you would face the same problem.

This SO post, might be slightly helpful although I don't think it is entirely correct: https://stackoverflow.com/questions/37964198/calling-fortran-intrinsics-in-gdb

Having said all that and because Modern Fortran does not create a new debugger but rather uses the one provided by the C/C++ extension I will be closing this issue.
