### ISSUE TITLE
linter stops working when external head file is included

### ISSUE THREAD

**Issue by jisuoqing** [krvajal/vscode-fortran-support#251]
Hi,

I found that when I include a head file, the linter stops working. A simple example is:

```
program test
include "mpi.h"
    implicit none

    integer :: A, B

    write(*,*) A

end program
```

The "unused variable" warning only shows up when the line `include "mpi.h"` is commented out.

**Comment by gnikit** [comment]
I suspect that the reason that this is occurring is because the linter works by performing a mock compilation of your Fortran file to find any potential errors. If that mock compilation terminates early because let's say you are missing a header file then you will get the impression that the linter has stopped working. In reality what this tells you is that you need to include in your `"fortran.includePaths"` the location of that `mpi.h`.

On a side note, if you are using OpenMPI this would probably still fail to lint. I don't think you pass the C header files for MPI to Fortran even if you are using the `-cpp` flag (for gfortran). You should either be using the module `use mpi_f08` or for the legacy format `include "mpif.h"`.

**Comment by gnikit** [comment]
I will be closing this but if you have any more issues feel free to reopen.

**Comment by Zhao-Mingbin** [comment]
Hi, I'm trying to use Visual Studio Code to develop Fortran MPI programs. However, while I can successfully build and run them just fine, it would be very helpful for me if I can use intellisense/autocompletion features for MPI (as well as other external modules). I have '/opt/intel/oneapi/mpi/2021.7.1/include' (which contains mpi_f08.mod) as part of fortran.includePaths in my settings.json. However, when I use mpi_f08, I get the problem message from VS Code Module "mpi_f08" not found in project. 

![image](https://user-images.githubusercontent.com/61232691/206895899-4339af4c-941f-48ab-8ee7-1fe784afa864.png)

The settings file is shown as bellow

![image](https://user-images.githubusercontent.com/61232691/206895945-45c9cad0-5006-47b0-a152-8a0bcccae980.png)

and the output log
![image](https://user-images.githubusercontent.com/61232691/206896018-d71c58ac-d6a7-434a-840e-3a0fd9919296.png)
