### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Cadelan** [krvajal/vscode-fortran-support#31]
What do i have to type in the user setting in order to being able to compile my code? I have typed in {"fortran.gfortranExecutable": "gfortran"} but it doesn't work, it says in the terminal it is an unknown command.

**Comment by krvajal** [comment]
I don't think this extension provide code compilation. In order to compile your code, it will depend on the build system you are using (like cmake, make, etc) and there are already many extensions that work very well will visual studio code. If it is the case that you are trying to compile and run a single file I suggest you  take a look at [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) that allows you to do that for many languages and adding Fortran wouldn't be so hard.
