### ISSUE TITLE
Problem with syntax highlight 

### ISSUE THREAD

**Issue by liaoj12** [krvajal/vscode-fortran-support#84]
Something wrong with the syntax highlight:

[
<img width="505" alt="screen shot 2018-07-04 at 7 28 31 pm" src="https://user-images.githubusercontent.com/6549969/42296188-9949b0a6-7fc0-11e8-801e-e47db0ee2cc3.png">
](url)

the angweight(ith, iphi) messed the syntax highlighting for the rest of the codes. If I delete the spaces on both sides of the "*" before the angweight(ith, iphi), then it works just fine (or adding a parentheses to wrap up the angweight also fix the problem)

**Comment by pedro-ricardo** [comment]
Thank you for the report, i'll take a look at it.
Could you type here those do loops so i can paste it in my editor and reproduce the error to debug it?

**Comment by pedro-ricardo** [comment]
The reason i ask you to paste the code here is that i've tryed to type it and as you can see i could not reproduce the error you are getting:
![screenshot_20180704_210744](https://user-images.githubusercontent.com/15893711/42296623-8f394172-7fce-11e8-9873-add7dc57f678.png)

**Comment by liaoj12** [comment]
@pedro-ricardo 
Hi, that's really weird, cause I typed it myself, it works just fine as well. I don't know what to do, sry.

**Comment by pedro-ricardo** [comment]
Well, maybe it is not caused by that code part it self but the interaction of it with something before in your file. 
Could you email me the file where the error happens?
If you can't do that but still wanna help l can guide you through some tests to help us find the error.
Please Let me know.

**Comment by liaoj12** [comment]
I don't think the issue is caused by the parts before it, because same problem appeared in a lot of places in the file, the fastest way to fix it I found yesterday was to add a space for the argument before the one that caused the problem.
But of course, please help me with some guidances of test to find the error, I would be happy to do so.

**Comment by pedro-ricardo** [comment]
Ok, then. The first thing i need you to do is to check the version of Modern Fortran extension you are using. It should be **1.3.1** like the picture below:
<img src="https://user-images.githubusercontent.com/15893711/42351919-d80d6864-808d-11e8-9228-b70a3bb9b53a.png" width="300">

If that is correct I need you to:
* Create a blank fortran file "test.f90"
* In your file (with the error happening), copy those 4 `DO` loops and paste them on "test.f90"
* Can you see the error?
  - Yes: Paste that in a comment here or send it by e-mail for me to debug that "test.f90"
  - No: Keep reading...
* Clean the file "test.f90"
* Back to you file, copy the next code part that embraces those loops. For example if there is an `if`block that starts before and ends after the loops, copy the whole block. Paste it on "test.f90".
* Can you see the error?
  - Yes: Paste here or send me to debug that "test.f90"
  - No: Keep reading...
* Repeat the cleaning / copy / paste / check steps until you see the error in "test.f90"
* If the only way you can see the error happening in "test.f90" is to copy your whole file in it, then i'm sorry but the only way i can fix it is if i have access to the file, as you didn't send it before i assume that  you can't do that, and i'm out of ideas.

**Comment by pedro-ricardo** [comment]
Any news on this @liaoj12 ?

**Comment by liaoj12** [comment]
Unfortunately, I tried your way but still no errors come up.
However, since all my files are in ".f" format, I'm not sure if that caused the issue. I wish I could do it again, but since all the files are written in fix-format style, it will take me so much time to just try to fix it to match the free-format style, so I won't be able to do that for right now.
Sorry about it.

**Comment by liaoj12** [comment]
No problem, I hope it could help.

**Comment by pedro-ricardo** [comment]
Got it @liaoj12 but it does not appear to be a problem in the extension but a problem with the way you typed it and the fix-format standards.
The extension for `.f` files folows the Fortran77 standards for fix-format style. that means: 
>  Col. 1    : Blank, or a "c" or "*" for comments
>  Col. 1-5  : Statement label (optional)
>  Col. 6    : Continuation of previous line (optional)
>  Col. 7-72 : Statements

In your file, as in the picture below:
![72char](https://user-images.githubusercontent.com/15893711/42543297-92e70a18-8481-11e8-9503-5c96cae2823e.png)
The above highlighted `h` is the 72nd character. Therefore beyond that point the code should be ignored (last rule from fix-format standards) and the extension marks it as a comment (grey or green in my case).
That said the highlight fails beyond that point because from that line forward an end bracket `)` is missing in the code.

**Comment by liaoj12** [comment]
<img width="593" alt="screen shot 2018-07-11 at 11 01 41 am" src="https://user-images.githubusercontent.com/6549969/42581050-e53c6b28-84f9-11e8-858e-c9bdf5d98d7e.png">
From the picture above, you see that the syntax highlighting works fine, but the "i" in "iphi" of angweight is at COL73 already!!!

**Comment by pedro-ricardo** [comment]
The rule written here will get the 73rd character, if that is a separator one (say space, comma, etc) then the characters beyond that point will be commented.
It means it is kind-of flexible ... if you want keep programming beyond that 72 limit than make sure that the 73nd character is not some sort of separator.
Try it yourself, go to the `Wavefnstone` line and add an space at 73rd character (just before `m2`) and see it getting commented, the `)` will be missing and the highlight will fail from that point onward.

Now i undersand what your error was, and i hope it is clear to you as well.
But ... **What is the fix you need me to do?**
In your opinion the highlight should be more rigid to the 72nd character? Be aware that this will ruin your current code, since you go beyond that point in several lines.
