### ISSUE TITLE
Linter can't find mod files in the current directory

### ISSUE THREAD

**Issue by certik** [krvajal/vscode-fortran-support#86]
First of all, thank you for creating and maintaining this extension.

I have to explicitly include directories with my mod files in settings.json, in my case like this:
```
    "fortran.includePaths": [
        "/home/certik/repos/hfsolver/src",
    ],
```
But my project has many subdirectories etc. I use cmake to manage it. Is there some better way to specify the paths for the linter? If not, is the intended usage that I will simply list all directories where one can find the .mod files my project specific settings for vscode?

Also, my project can be build both in tree and out of tree using cmake. In the out of tree build, the mod files will be at different location. Is there a solution to that?

Thanks for any tips.

**Comment by krvajal** [comment]
Hello, that's an interesting problem and I will definitively look into it.

**Comment by krvajal** [comment]
I think one possible solution, besides the obvious of adding each directory entry, is to allow you to use glob expressions when specifying the `includePaths`. For example, given the following filesystem structure
```sh
projectRoot/
├── src
    ├── utils
	├── modules
    	├── module_a
    	├── module_b
```
and the following config
```
"includePath": ["src/**/"] 
```
the extension will add to the search path the following directories
```
<projectRoot>/src/
<projectRoot>/src/utils
<projectRoot>/src/modules
<projectRoot>/src/modules/module_a
<projectRoot>/src/modules/module_b
```
Is that good enough to solve your use case or I am getting something wrong?

**Comment by krvajal** [comment]
^ @certik

**Comment by pedro-ricardo** [comment]
> recursively searching in includePaths would be a nice-to-have.

Issues #159 and #132 also request the include folders to suppport relative paths

**Comment by gnikit** [comment]
@certik took me some time to get back to this but currently we don't have native support with CMake. At some point I will have to add it but I am slightly short on time right now.

With regards to the question at hand, I have gone ahead and pushed `v2.6.1` on the VS marketplace which adds variable interpolation and glob support so you could pass an include directory like the one mentioned above `src/**` or `${workspaceFolder}/include/**`. Just be careful not to pass too broad of a glob pattern for a very nested directory because `gfortran` has a limit to the number of arguments it can have when compiling
